spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - 'file:../service-config-dev/{application}'
            - 'file:../service-config-dev'
          add-label-locations: false
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8081}
