FIREBASE_HOST: https://c7d2-105-246-242-152.ngrok-free.app
SPRING_BOOT_ADMIN_URL: https://75fb-105-246-242-152.ngrok-free.app
SERVICE_BASE_URL: https://mthoko-config-server-65b97ffd435b.herokuapp.com
