server:
  port: ${PORT:8081}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mthoko78/service-config.git
          default-label: main
          force-pull: true
          refreshRate: 120
          cloneOnStart: true
          searchPaths: '{application}'
          skipSslValidation: true
          strict-host-key-checking: false
  boot:
    admin:
      client:
        username: ${SPRING_BOOT_ADMIN_USERNAME:admin}
        password: ${SPRING_BOOT_ADMIN_PASSWORD:password}
        url: ${SPRING_BOOT_ADMIN_URL:http://localhost:8084}
        instance:
          service-url: ${SERVICE_BASE_URL}/
          base-service-url: ${SERVICE_BASE_URL}/
          management-url: ${SERVICE_BASE_URL}/actuator
          health-url: ${SERVICE_BASE_URL}/actuator/health

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'